# Generated by Django 5.0.4 on 2024-04-22 10:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodwareProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "foodware_project",
            },
        ),
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "db_table": "locale",
            },
        ),
        migrations.CreateModel(
            name="FoodwareProjectJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Location", "Locations"), ("Route", "Routes")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Error", "Error"),
                            ("Success", "Success"),
                        ]
                    ),
                ),
                ("last_error", models.TextField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodware.foodwareproject",
                    ),
                ),
            ],
            options={
                "db_table": "foodware_project_job",
            },
        ),
        migrations.AddConstraint(
            model_name="locale",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_locale"),
        ),
        migrations.AddField(
            model_name="foodwareproject",
            name="locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foodware.locale"
            ),
        ),
    ]
