# Generated by Django 5.0.3 on 2024-03-12 01:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodwareModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
                ("padlet_board_id", models.CharField(blank=True, default="")),
                ("padlet_board_url", models.URLField(blank=True, default="")),
            ],
            options={
                "db_table": "model",
            },
        ),
        migrations.CreateModel(
            name="FoodwareModelBin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("external_source", models.CharField()),
                ("external_id", models.CharField(blank=True, default="")),
                ("external_name", models.CharField(blank=True, default="")),
                ("external_category", models.CharField()),
                ("name", models.CharField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Commercial Foodservice", "Commercial Foodservice"),
                            ("Community Center", "Community Center"),
                            ("Library", "Library"),
                            ("Lodging", "Lodging"),
                            ("Mall or Shopping Center", "Malls And Shopping Centers"),
                            ("Medical Center", "Medical Center"),
                            ("Office Space", "Office"),
                            ("Post Office", "Post Office"),
                            ("School", "School"),
                            (
                                "Grocery Store, Drugstore, or Pharmacy",
                                "Retail Food And Drug",
                            ),
                            ("Transportation", "Transportation"),
                            ("Zoo or Aquarium", "Zoo Or Aquarium"),
                        ]
                    ),
                ),
                ("capacity", models.IntegerField(null=True)),
                ("coords", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="FoodwareModelJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Location", "Locations"), ("Route", "Routes")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Error", "Error"),
                            ("Success", "Success"),
                        ]
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "job",
            },
        ),
        migrations.AddConstraint(
            model_name="foodwaremodel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_model_name"
            ),
        ),
        migrations.AddField(
            model_name="foodwaremodelbin",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foodware.foodwaremodel"
            ),
        ),
        migrations.AddField(
            model_name="foodwaremodeljob",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foodware.foodwaremodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="foodwaremodelbin",
            constraint=models.UniqueConstraint(
                fields=("model", "external_source", "external_id"),
                name="unique_location",
            ),
        ),
    ]
