# Generated by Django 5.0.6 on 2024-05-20 17:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodwareProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "foodware_project",
            },
        ),
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "locale",
            },
        ),
        migrations.CreateModel(
            name="PoiCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "poi_cache",
            },
        ),
        migrations.CreateModel(
            name="PoiParentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "poi_parent_category",
            },
        ),
        migrations.CreateModel(
            name="PoiProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "poi_provider",
            },
        ),
        migrations.CreateModel(
            name="PoiProviderCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "poi_provider_category",
            },
        ),
        migrations.CreateModel(
            name="FoodwareProjectBin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, default="")),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("Undetermined", "Undetermined"),
                            ("Indoor", "Indoor"),
                            ("Outdoor", "Outdoor"),
                            ("Excluded", "Excluded"),
                        ],
                        default="Undetermined",
                    ),
                ),
                ("name", models.CharField(blank=True, default="")),
                ("external_categories", models.JSONField()),
                ("formatted_address", models.CharField(blank=True, default="")),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("features", models.JSONField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodware.foodwareproject",
                    ),
                ),
            ],
            options={
                "db_table": "foodware_project_bin",
            },
        ),
        migrations.CreateModel(
            name="FoodwareProjectJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at_utc", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Location", "Locations"), ("Route", "Routes")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Error", "Error"),
                            ("Success", "Success"),
                        ]
                    ),
                ),
                ("last_error", models.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodware.foodwareproject",
                    ),
                ),
            ],
            options={
                "db_table": "foodware_project_job",
            },
        ),
        migrations.AddConstraint(
            model_name="locale",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_locale"
            ),
        ),
        migrations.AddField(
            model_name="foodwareproject",
            name="locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.locale",
            ),
        ),
        migrations.AddField(
            model_name="poicache",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.foodwareproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="poiparentcategory",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_poi_parent_category"
            ),
        ),
        migrations.AddField(
            model_name="poicache",
            name="parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiparentcategory",
            ),
        ),
        migrations.AddField(
            model_name="foodwareprojectbin",
            name="parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiparentcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="poiprovider",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_poi_provider"
            ),
        ),
        migrations.AddField(
            model_name="poicache",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiprovider",
            ),
        ),
        migrations.AddField(
            model_name="foodwareprojectbin",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiprovider",
            ),
        ),
        migrations.AddField(
            model_name="poiprovidercategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiparentcategory",
            ),
        ),
        migrations.AddField(
            model_name="poiprovidercategory",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foodware.poiprovider",
            ),
        ),
        migrations.AddConstraint(
            model_name="poicache",
            constraint=models.UniqueConstraint(
                fields=("project", "provider", "parent_category"),
                name="unique_poi_cache_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodwareprojectbin",
            constraint=models.UniqueConstraint(
                fields=(
                    "project",
                    "provider",
                    "external_id",
                    "name",
                    "formatted_address",
                ),
                name="unique_foodware_project_bin",
            ),
        ),
        migrations.AddConstraint(
            model_name="poiprovidercategory",
            constraint=models.UniqueConstraint(
                fields=("provider", "name"), name="unique_poi_provider_category"
            ),
        ),
    ]
